---
- name: Install the  wget utility
  yum:
    name: wget

- name: Installing the java Package
  yum:
    name: "{{java.VERSION}}"
    state: latest
  become: true

- name: Downloading the jenkins.repo
  get_url:
    url: "{{jenkins.repo_URL}}"
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Importing Jenkins Key
  rpm_key:
    state: present
    key: "{{jenkins.rpm_key}}"
  become: true

- name: Installing the Jenkins
  yum:
    name: jenkins
    state: present
  become: true

- name: Start and Enable the Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: true
  become: true

- name: Sleep for 30 seconds and continue with play
  wait_for: timeout=30

- name: Get the init password Jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result
  become: true

- name: Printing the init password Jenkins
  debug:
    var: result.stdout

