---
# vars file for jenkins
java:
  VERSION: "java-1.8.0-openjdk"

jenkins:
  repo_URL: "http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo"
  rpm_key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
